import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Navbar from "@/components/Nav/Navbar";
import Footer from "@/components/Footer/Footer";
const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
  weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={manrope.variable}>
       
          <main style={{ paddingTop: "80px" }}>
            {children}
          </main>
         
        
      </body>
    </html>
  );
}
